apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinybench
  namespace: tiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinybench
  template:
    metadata:
      labels:
        app: tinybench
        deploy: deploy-22-01-26-08-29-35
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/tinybench:latest
          imagePullPolicy: Always

          args: 
          - --zone
          - az-eastus2
          - --region
          - East

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
