apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinybench
  namespace: tiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinybench
  template:
    metadata:
      labels:
        app: tinybench
        version: beta-0125-1848
        deploy: 22-01-25-18-48-19
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/tinybench:latest
          imagePullPolicy: Always

          args: 
          - --zone
          - az-eastus2
          - --region
          - East

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
