apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: tinybench
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

metadata:
  namespace: tiny
  labels:
    app: tinybench
  name: tinybench-np
