apiVersion: v1
kind: Service
metadata:
  name: tinybench
  namespace: tiny
  labels:
    app: tinybench
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: tinybench
