apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: {{gitops.name}}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

metadata:
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}
  name: {{gitops.name}}-np
